[Feature/MarketPriceModal] 시세 모달창 구현
wecode-bootcamp-korea/29-2nd-GREAM-frontend pull request #10
Opened 2022-02-20 18:32 UTC by jihongzzang

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 아이디, 비밀번호 입력창을 사용한 로그인 기능 구현 (예시)

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 로그인 입력 데이터 유효성 검사 (예시 - 프론트)
- 입력창에 변화가 일어날 때 마다 유효성 검사 함수가 실행된다.
- 유효성 검사 함수의 반환값(boolean)에 따라 버튼의 배경색과 disabled 속성이 변화한다.
- 테스트 방법 : `/login` 페이지 이동 >>> 로그인 input 데이터 입력

2. 로그인 데이터 처리 (예시 - 백엔드)
- 조건문과 정규식을 이용한 email과 password 유효성 검사를 진행
- 유효섬 검사를 통과하지 못 할 경우 에러 메시지를 반환 예외 처리 구현

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 사용자가 발생시킬 수 있는 다양한 예외 케이스에 대해 고민하게 되었습니다. (예시)
- 문자열 데이터 입력 시 마지막에 빈 문자열이 포함되어 있는 경우 데이터 처리가 올바르게 되지 않아 유효성 검사에 빈 문자열 제거하는 로직을 추가하였습니다. (예시)

<br />

## :: 기타 질문 및 특이 사항
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시)

2022-02-20 18:35 UTC, jihongzzang commented on src/pages/ProductDetail/MarketPriceModal.js
> +  const [selectedSize, setSelectedSize] = useState({
선언된 selected 버튼을 활용하여 모달창 내부 sort 함수 구현때문에 삭제하지못했습니다.

2022-02-20 18:36 UTC, jihongzzang commented on src/pages/ProductDetail/MarketPriceModal.js
> +    console.log(e.currentTaget.name);
선언된 selected 버튼을 활용하여 모달창 내부 sort 함수 구현와중에 있어 삭제하지못했습니다.

2022-02-21 04:56 UTC, younuk23 commented
branch에서 다른 2개의 브랜치가 나오다보니 파일 체인지에 모든 내역이 다 잡혀버려서 제가 리뷰를 하기가 힘들어서, 원본 브랜치 머지되고 나면 리뷰하도록 하겠습니다! 일단 추가기능 구현중 라벨 붙여주시고, 머지되고 rebase 까지 다 완료되면 리뷰요청 붙여주시면 확인하겠습니다!

2022-02-22 07:49 UTC, jihongzzang commented
rebase 완료

2022-02-22 08:30 UTC, younuk23 approved these changes
LGTM 👍

2022-02-22 08:43 UTC, younuk23 commented
Conflict 해결해주세요!

2022-02-23 02:06 UTC, younuk23 requested changes
지홍님 패키지락 컨플릭 제대로 해결 안된 것 같네요! 이러면 전체적으로 다 문제 생길 수 있어서 꼼꼼하게 확인해주세요!

아래 코멘트 참고해서 해결해주세요!
- lock 파일은 패키지 변화 히스토리 트리가 담겨있어서 프로젝트 버전이랑 함께 관리 되어야 합니다. lock 파일이 없다면 현재 프로젝트에서 사용하고 있는 버전이 아닌 최신 버전이 계속 설치됩니다.
- lock.json 파일 컨플릭트 해결 방법
    1. package.json 파일의 컨플릭트 해결
    2. `npm install --package-lock-only`
- 참고 링크 : [https://dltlabs.medium.com/package-json-vs-package-lock-json-c8d5deba12cb](https://dltlabs.medium.com/package-json-vs-package-lock-json-c8d5deba12cb)

2022-02-23 02:15 UTC, jihongzzang commented
> 지홍님 패키지락 컨플릭 제대로 해결 안된 것 같네요! 이러면 전체적으로 다 문제 생길 수 있어서 꼼꼼하게 확인해주세요!
> 
> 아래 코멘트 참고해서 해결해주세요!
> 
> * lock 파일은 패키지 변화 히스토리 트리가 담겨있어서 프로젝트 버전이랑 함께 관리 되어야 합니다. lock 파일이 없다면 현재 프로젝트에서 사용하고 있는 버전이 아닌 최신 버전이 계속 설치됩니다.
> * lock.json 파일 컨플릭트 해결 방법
>   
>   1. package.json 파일의 컨플릭트 해결
>   2. `npm install --package-lock-only`
> * 참고 링크 : https://dltlabs.medium.com/package-json-vs-package-lock-json-c8d5deba12cb

2022-02-23 02:16 UTC, jihongzzang commented
npm install --package-lock-only 혹시 이파일을 설치하면 되는건가용??

2022-02-23 02:16 UTC, jihongzzang commented
@younuk23 npm install --package-lock-only 혹시 이파일을 설치하면 되는건가용??

2022-02-23 02:28 UTC, younuk23 approved these changes
네 package-lock에 conflict 발생 시 package-lock만 새로 install 하는 방식으로 해결하면 됩니다!

2022-02-23 02:28 UTC, merged