[feature/loginKakao] Add: Post Kakao login authorize code to server
wecode-bootcamp-korea/29-2nd-GREAM-frontend pull request #11
Opened 2022-02-21 10:06 UTC by pkw-May

## :: 최근 작업 주제
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표
- Kakao Social login API 연동

<br />

## :: 구현 사항 설명
#### 1. Kakao Login API 활용하여 로그인 진행
1) REST API 방식으로 Kakao Login 인가코드 요청
  a. Kakao developers에 개인 어플리케이션 등록 후 발행된 <앱 REST API 키> 확인
  b. Kakao로부터 로그인 인가코드를 전달받을 < REDIRECT URI > 설정
  c. 로그인 모달창의 로그인 버튼 a태그 href에 인가코드 요청 URL 입력
    - Kakao 인가코드 발행 URL에 1)번과 2)번의 값을 query string 형식으로 포함하여, 해당 URL로 이동

2) GET 방식으로 Backend server에 인가코드 전달 후 JWT 값 받기
  a. 1-b)에서 설정한 < REDIRECT URI > 페이지를 구성하는 컴포넌트(`OathHandler.js`)를 Router.js에 추가
  b. Kakao에서 전송된 인가코드를 parsing하는 함수 추가
    - `useLocation()` hook의 `search()` 함수를 활용하여, URL의 querystring을 parsing
    - `slice()`함수를 활용하여, parsing된 querystring중 인가코드 영역만 변수에 할당
  c. 변수에 할당된 인가코드를 Backend server API URL의 querystring으로 포함하여 GET방식으로 전송
  d. Backend server로부터 response 값으로 전송된 'JWT'를 sessionStorage에 저장

- 테스트 방법 : `/list` 페이지 이동 >>> 로그인 버튼 선택 >>> 카카오 로그인 진행 >>> `/oauth` 페이지 콘솔창에 `sessionStorage.JWT` 입력

## :: 추가 구현 사항
- 로그인 버튼 선택의 경우, 상세페이지 관심상품 추가 OR 상세페이지 구매버튼 선택의 경우 로그인 완료 이후 이동 페이지 제어
  - useHistory() hook 활용

<br />

## :: 성장 포인트
- Kakao social login API의 인가코드 발급, 인증토큰 발급, 사용자 데이터 요청 구조를 이해하게 됨
- REDIRECT URI에 query string이 추가되는 경우 router에서 인식할 수 있도록 추가해야함을 알게 됨
- useLocation() hook을 활용하는 방법을 터득함
- Backend server에서 Python으로 인증토큰을 발급받고, 사용자 데이터 요청하는 구조를 이해하게 됨

2022-02-21 11:59 UTC, pkw-May commented on src/components/Nav/Login/OauthHandler.js
> +  }, []);
@younuk23 한 바퀴만 돌리고 싶은데도.. dependency를 반드시 특정 값으로 할당해주어야 하나요?

2022-02-22 04:43 UTC, younuk23 requested changes
고생하셨습니다 경원님 리뷰 확인 및 반영진행해주세요!

2022-02-22 04:43 UTC, younuk23 commented on src/components/Nav/Login/Login.js
> +          onKeyUp={e => e.key === 'Escape' && closeLoginModal()}
디테일 너무 좋네요!! 
조금 더 더하자면, && or || 등 연산자와 if의 가장 큰 차이점은 결과로 값을 만드냐 안만드냐 입니다.
&&연산자등은 평가 결과 특정 값을 만들어내고 if else 구문은 값을 만들지 않고 내부에 쓰인 코드를 실행하는 식으로 동작합니다.

이경우 동작상의 차이는 없지만 closeLoginModal()의 값이 필요한게 아니라 저걸 호출하는 구문이 필요한 것이므로 개인적으로 if문을 쓰는것을 조금 더 권장드립니다!

내용 한번 참고해보시고 이해 안되시면 질문주세요!

2022-02-22 04:43 UTC, younuk23 commented on src/components/Nav/Login/Login.js
> +            <button onClick={() => closeLoginModal()}>X</button>
```suggestion
            <button onClick={closeLoginModal}>X</button>
```

굳이 새로운 arrow function 만들 필요가 없겠네요!

2022-02-22 04:43 UTC, younuk23 commented on src/components/Nav/Login/OauthHandler.js
> +  }, []);
네 useEffect에서 사용하는 값이 있다면, dependency array에 넣어주는것이 예상치 못한 동작을 안하게 되는 방법입니다. 이 경우에는 location이라는 값을 dependency에 넣어주게 되면 어차피 이 컴포넌트가 마운트 되고 나서 이 안에서 location을 변화시키는 경우는 없기 때문에 한번만 동작하게 되겠네요!

이 부분에 대해서 조금 더 디테일 하게 알고 싶으시면 useEffect 완벽 가이드 라는 제목으로 구글에 검색해보시면 
Dan abramov가 작성한 아티클 번역해둔 것을 볼 수 있으실겁니다! 좀 더 공부하고 싶으실 때 시간내셔서 한번 공부해보세요!

2022-02-22 06:18 UTC, pkw-May commented on src/components/Nav/Login/OauthHandler.js
> +  }, []);
오... 감사하비낟!!!

2022-02-22 06:19 UTC, pkw-May commented on src/components/Nav/Login/Login.js
> +          onKeyUp={e => e.key === 'Escape' && closeLoginModal()}
오..... 이거 차이를 이제서야 알게됐어요ㅠㅠ *-* 감사합니당!!

2022-02-22 07:04 UTC, younuk23 approved these changes
LGTM 👍

2022-02-22 07:04 UTC, merged