[29기 박혜린] 상세페이지 모달창 컴포넌트 개별화 작업  및 제품 사이즈 별 가격 담기 기능 구현
wecode-bootcamp-korea/29-2nd-GREAM-frontend pull request #13
Opened 2022-02-21 12:57 UTC by effypark

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 백엔드 통신하여 데이터 재배치 후 총 3개의 모달창에서 중복되어 사용되는 버튼과 모달창을 한 컴포넌트로 재사용하여 개별적으로 관리 

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 백엔드 통신하여 데이터 재배치
- 해당 제품 사이즈 관련 API GET 요청하여 데이터 받아서 재배치
- useParams 사용하여 제품 Id 값으로 동적 라우팅 

2. 중복되는 모달창, 그 안의 컴포넌트를 한 컴포넌트로 재사용하여 개별적으로 관리
- props 를 넘겨서 조건을 걸어 한 컴포넌트를 재사용하여 간편하게 활용

3. 선택한 사이즈 별 가격 담기

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 중복되는 부분을 한 컴포넌트로 재사용하여 간편하게 관리 할 수 있게 된 것. 독립적으로 사용할 건 props 를 넘겨주어 조건에 따라 다른 데이터를 보여주고, 담기게 할 수 있었다.

<br />

## :: 기타 질문 및 특이 사항
- 여전히 state 남용이 많은 것 같습니다. 더 실용적인 state 관리를 하고 싶은데, 더 찾아보고 리팩토링 하고자 합니다.

2022-02-21 12:59 UTC, ghost commented on src/pages/ProductDetail/ProductDetailInfo/ProductDetailInfo.js
> +  console.log(productBox.recent_price);
__[ESLint]__ Unexpected console statement. ([view](https://sider.review/gh/repos/459037924/pulls/13#issue-6565170))

<details>

| Rule | Severity | Recommended |
| ---- | -------- | ----------- |
| `no-console` | `warn` | No |

References:
- <https://eslint.org/docs/rules/no-console>

You can [close this issue](https://sider.review/gh/repos/459037924/pulls/13#issue-6565170) if no need to fix it. [Learn more](https://help.sider.review/getting-started/working-with-issues).

</details>

2022-02-21 12:59 UTC, ghost commented on src/pages/ProductDetail/ProductDetailInfo/ProductDetailInfo.js
> +  console.log(pickedSize);
__[ESLint]__ Unexpected console statement. ([view](https://sider.review/gh/repos/459037924/pulls/13#issue-6565171))

<details>

| Rule | Severity | Recommended |
| ---- | -------- | ----------- |
| `no-console` | `warn` | No |

References:
- <https://eslint.org/docs/rules/no-console>

You can [close this issue](https://sider.review/gh/repos/459037924/pulls/13#issue-6565171) if no need to fix it. [Learn more](https://help.sider.review/getting-started/working-with-issues).

</details>

2022-02-22 04:50 UTC, younuk23 requested changes
고생하셨습니다 혜린님! 리뷰 확인 해주시고 큰 부분은 없고 세부적으로 다듬는 부분이라서 전반적으로 코드보고 한번씩 셀프 리팩토링 진행해주세요!

2022-02-22 04:50 UTC, younuk23 commented on src/pages/ProductDetail/ProductDetail.js
> +  // }, []);
불필요한 주석은 삭제해주세요!
코드가 주석처리된 채로 남아있다면 필요한 상황에 제대로 사용되거나 삭제되는 일은 거의 없고 결국 계속 남아있게 됩니다.
그러다보면 이제 작성한 사람이 아닌 다른 개발자는 필요한 코드라서 주석처리한게 아닐까? 라는 생각으로 지우지 못하고
결국 그 누구도 왜 있는지는 모르면서 계속 남아있는 불필요한 레거시가 되어버립니다! 
따라서 반드시 필요한 경우가 아니면 코드를 주석처리하기보다는 삭제해주시고 만약 다시 보고싶다면 커밋 이력에 잘 남겨뒀다가 원하는 시점에 다시 보면 됩니다!

2022-02-22 04:50 UTC, younuk23 commented on src/pages/ProductDetail/ProductDetailInfo/ProductDetailInfo.js
> +  console.log('pickedSize', pickedSize);
console 삭제해주세요!

2022-02-22 04:50 UTC, younuk23 commented on src/pages/ProductDetail/ProductDetailInfo/ProductDetailInfo.js
> +  const sizeInit = '모든 사이즈';
상수값이라면 상수값 네이밍 적용해주세요!

2022-02-22 04:50 UTC, younuk23 commented on src/pages/ProductDetail/ProductDetailInfo/PurchaseModal/ModalContents.js
> +        ) : (
```suggestion
          <SizeBtn
            key={index}
            value={x.price}
            name={x.size}
            onClick={onClick}
            changedColor={changedColor}
            bold={changeColor[x.size]}
          >
            <Box>
              <Size>{x.size}</Size>
              <Price>{x.price}</Price>
            </Box>
          </SizeBtn>
```
전체적으로 삼항연산자 적용안하고 저렇게도 표현할 수 있을 것 같네요!

2022-02-22 04:50 UTC, younuk23 commented on src/pages/ProductDetail/ProductDetailInfo/PurchaseModal/ModalInBox.js
> +// import React from 'react';
?!

2022-02-22 05:32 UTC, effypark commented on src/pages/ProductDetail/ProductDetailInfo/PurchaseModal/ModalInBox.js
> +// import React from 'react';
삭제할게요,,,

2022-02-22 06:17 UTC, effypark commented on src/pages/ProductDetail/ProductDetailInfo/ProductDetailInfo.js
> +  console.log('pickedSize', pickedSize);
넹

2022-02-22 06:18 UTC, effypark commented on src/pages/ProductDetail/ProductDetail.js
> +  // }, []);
넵~

2022-02-22 06:19 UTC, effypark commented on src/pages/ProductDetail/ProductDetailInfo/ProductDetailInfo.js
> +  const sizeInit = '모든 사이즈';
ㅔ네~

2022-02-22 06:23 UTC, effypark commented on src/pages/ProductDetail/ProductDetailInfo/PurchaseModal/ModalContents.js
> +        ) : (
네!

2022-02-22 08:22 UTC, younuk23 approved these changes
LGTM 👍

2022-02-22 08:22 UTC, merged