[Feature/productDetailInfo] 상세페이지 상품 정보 상단 레이아웃
wecode-bootcamp-korea/29-2nd-GREAM-frontend pull request #4
Opened 2022-02-16 05:54 UTC by effypark

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 상품 상세페이지 상품 정보 레이아웃 
- 상품 구매 버튼 클릭 시 모달창 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 상품 상세페이지 상품 정보 레이아웃
2. 상품 구매 버튼 클릭 시 모달창 구현 (예정)

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)

<br />

## :: 기타 질문 및 특이 사항

2022-02-16 08:09 UTC, younuk23 requested changes
고생하셨습니다 혜린님 스타일드 컴포넌트 잘 활용하시고 컴포넌트도 잘 분리해주셨네요~!!
- 컨플릭 해결 및 리뷰 확인 및 반영해주세요~!! 
- 커밋 리베이스해서 하나로 만들어주세요~!
- PR 본문은 `[이름] 한줄요약` 식으로 작성해주세요 :)

2022-02-16 08:09 UTC, younuk23 commented on src/pages/ProductDetail/ProductDetailInfo/Button.js
> +  return <StyledButton {...props}>{children}</StyledButton>;
👍

2022-02-16 08:09 UTC, younuk23 commented on src/pages/ProductDetail/ProductDetailInfo/Button.js
> +  background-color: ${props => props.theme.redColor};
```suggestion
  background-color: ${({theme})=> theme.redColor};
```
구조분해할당해서 적용해보세요~!!

2022-02-16 08:09 UTC, younuk23 commented on src/pages/ProductDetail/ProductDetailInfo/Button.js
> +    `}
```suggestion
  ${({cell, theme}) =>
    css`
      border-radius: ${theme.btnRadius};
      background-color: ${cell ? theme.greenColor : theme.redColor}
    `}
```
위와 같이도 표현할 수 있습니다~!!

2022-02-16 08:09 UTC, younuk23 commented on src/pages/ProductDetail/ProductDetailInfo/Button.js
> +const StyledButton = styled.button`
컴포넌트와 스타일드컴포넌트 사이에 공백 한줄 있으면 가독성이 좀 더 좋겠네요!

2022-02-16 08:09 UTC, younuk23 commented on src/pages/ProductDetail/ProductDetailInfo/Button.js
> +    `}
다른 부분도 응용할 수 있는 부분 응용해보세요 :)

2022-02-16 08:09 UTC, younuk23 commented on src/pages/ProductDetail/ProductDetailInfo/ProductDetailInfo.js
> +  // };
불필요한 주석은 삭제해주세요!
코드가 주석처리된 채로 남아있다면 필요한 상황에 제대로 사용되거나 삭제되는 일은 거의 없고 결국 계속 남아있게 됩니다.
그러다보면 이제 작성한 사람이 아닌 다른 개발자는 필요한 코드라서 주석처리한게 아닐까? 라는 생각으로 지우지 못하고
결국 그 누구도 왜 있는지는 모르면서 계속 남아있는 불필요한 레거시가 되어버립니다! 
따라서 반드시 필요한 경우가 아니면 코드를 주석처리하기보다는 삭제해주시고 만약 다시 보고싶다면 커밋 이력에 잘 남겨뒀다가 원하는 시점에 다시 보면 됩니다!

2022-02-16 08:50 UTC, effypark commented on src/pages/ProductDetail/ProductDetailInfo/ProductDetailInfo.js
> +  // };
넵~

2022-02-16 08:50 UTC, effypark commented on src/pages/ProductDetail/ProductDetailInfo/Button.js
> +const StyledButton = styled.button`
넵~

2022-02-16 09:03 UTC, effypark commented on src/pages/ProductDetail/ProductDetailInfo/Button.js
> +    `}
넵~

2022-02-16 09:03 UTC, effypark commented on src/pages/ProductDetail/ProductDetailInfo/Button.js
> +  background-color: ${props => props.theme.redColor};
네~

2022-02-17 04:41 UTC, younuk23 commented
혜린님 아직 수정중이신 PR인가요??

2022-02-17 08:16 UTC, effypark commented
연욱님 sider 하나 걸린거 라틴어라 철자 오류는 아니라 수정은 안했습니다. 이외에 리뷰 반영해서 수정했어요~

2022-02-17 09:47 UTC, younuk23 approved these changes
LGTM 👍

2022-02-17 09:48 UTC, merged