[feature/theme] 공용 style 속성, 라이브러리, 이미지 추가
wecode-bootcamp-korea/29-2nd-GREAM-frontend pull request #5
Opened 2022-02-16 06:16 UTC by pkw-May

## :: 최근 작업 주제
- [x] 기능 추가

<br />

## :: 추가 사항
1. mixin.js 추가
- flexAlignCenter 변수 추가
    ```display: flex;, align-items: center;```

2. favicon 이미지 추가
- public/images에 favicon 이미지 2개 추가

3. fontawesome 라이브러리 설치
    ```npm i --save @fortawesome/fontawesome-svg-core
npm install --save @fortawesome/free-solid-svg-icons
npm install --save @fortawesome/react-fontawesome```

<br />

## :: 기타 질문 및 특이 사항
- 팀원들과 합의된 사항입니다.

2022-02-16 08:10 UTC, younuk23 requested changes
리뷰 확인해주세요~!

2022-02-16 08:10 UTC, younuk23 commented on src/styles/mixin.js
> +export const flexAlignCenter = css`
css import 안되있어서 에러 발생할 것 같네요!

2022-02-16 08:56 UTC, pkw-May commented on src/styles/mixin.js
> +export const flexAlignCenter = css`
해결했습니다!

2022-02-17 04:36 UTC, younuk23 approved these changes
LGTM 👍

2022-02-17 04:37 UTC, merged