[Feature/favoritesBtn] 관심상품 담기 버튼 생성 및 모달
wecode-bootcamp-korea/29-2nd-GREAM-frontend pull request #6
Opened 2022-02-16 10:32 UTC by jihongzzang

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 아이디, 비밀번호 입력창을 사용한 로그인 기능 구현 (예시)

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 로그인 입력 데이터 유효성 검사 (예시 - 프론트)
- 입력창에 변화가 일어날 때 마다 유효성 검사 함수가 실행된다.
- 유효성 검사 함수의 반환값(boolean)에 따라 버튼의 배경색과 disabled 속성이 변화한다.
- 테스트 방법 : `/login` 페이지 이동 >>> 로그인 input 데이터 입력

2. 로그인 데이터 처리 (예시 - 백엔드)
- 조건문과 정규식을 이용한 email과 password 유효성 검사를 진행
- 유효섬 검사를 통과하지 못 할 경우 에러 메시지를 반환 예외 처리 구현

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 사용자가 발생시킬 수 있는 다양한 예외 케이스에 대해 고민하게 되었습니다. (예시)
- 문자열 데이터 입력 시 마지막에 빈 문자열이 포함되어 있는 경우 데이터 처리가 올바르게 되지 않아 유효성 검사에 빈 문자열 제거하는 로직을 추가하였습니다. (예시)

<br />

## :: 기타 질문 및 특이 사항
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시)

2022-02-17 05:25 UTC, younuk23 requested changes
코드 스타일도 깔끔해지시고, 이것저것 잘 공부하면서 적용 잘 하시는 것 같아서 너무 좋습니다 👍
리뷰 확인 및 반영해주세요~!

2022-02-17 05:25 UTC, younuk23 commented on src/pages/ProductDetail/FavoriteBtn.js
> +  ...rest
Good 👍

2022-02-17 05:25 UTC, younuk23 commented on src/pages/ProductDetail/FavoriteBtn.js
> +};
defaultProps도 잘 찾아보고 적용하셨네요 👍
이 방법도 있고, 구조분해할당하면서 바로 defualt value 설정하는 방법도 있습니다 참고하시면 됩니다

2022-02-17 05:25 UTC, younuk23 commented on src/pages/ProductDetail/FavoriteBtn.js
> +  }}
```suggestion
  ${({ theme, color, outline }) => css`
      background: ${theme.palette[color]};
      ${outline &&
        css`
          color: ${selected};
          background: none;
          border: 1px solid ${selected};
        `}
    `;
  }
  ```
  이런 방식으로도 표현할 수 있습니다!

2022-02-17 05:25 UTC, younuk23 commented on src/pages/ProductDetail/FavoriteBtn.js
> +const sizes = {
```suggestion
const SIZES = {
```

상수인것 같네요, 상수임이 표현되도록 네이밍 컨벤션 잘 적용해주세요!

2022-02-17 05:25 UTC, younuk23 commented on src/pages/ProductDetail/FavoriteModal.js
> +  return (
```suggestion
  if (!visible) return null;

  return (
```

다른 문맥들끼리는 공백을 통해서 가독성에 신경써주세요

2022-02-17 05:25 UTC, younuk23 commented on src/pages/ProductDetail/FavoriteModal.js
> +      <ModalWrapper onClick={e => e.stopPropagation()}>
event bubbling 잘 공부하시고 막아서 원하는대로 동작 잘 시키셨네요!!
이런식으로 하는 방식도 있고, 버블링은 막지 않으면서 event.target.contains method를 활용해서 이벤트가 
Wrapper 바깥에서 일어났는지만 판단하는 방식도 있습니다.

권장드리는 방법은 e.target.contains 활용하신는 방향을 권장드립니다.
event bubbling을 막을경우 추후 user tracking tool등이 제대로 동작되지 않는 등의 문제가 있기 때문에,
자연스러운 동작인 버블링은 최대한 막지 않으면서 원하는 동작을 수행하는 방향으로 진행해주세요!

2022-02-17 05:25 UTC, younuk23 commented on src/pages/ProductDetail/ProductDetail.js
> +    return renderNum;
```suggestion
    if (productInterestedNum === undefined) {
      return 0;
    }
    if (productInterestedNum >= 0) {
      return productInterestedNum;
    }
    if (productInterestedNum >= 1000) {
      reutrn productInterestedNum.toLocaleString();
    }
    if (productInterestedNum >= 10000) {
      return parseFloat((productInterestedNum / 10000).toFixed(1)) + '만';
    }

    return 0
```

위와 같은 식으로도 표현할 수 있습니다 참고해주세요~!

2022-02-17 05:26 UTC, younuk23 commented
리베이스 적용해주세요~!

2022-02-17 05:31 UTC, younuk23 commented
- 4번 기능 구현 이전에 멘토님의 피드백을 받은것들을 반영한 뒤에 새로운 브랜치를 파서 4번 기능을 구현하는것이 어떤지 궁금합니다.
=> 완전 좋습니다 👍
- 버튼컴포넌트를 구성하였는데 버튼 내부에 들어가는 content (span 태그의 요소들) 은 다양하고 화면에 렌더링 되는 디스플레이도 조금씩 달라서 컴포넌트만 구성하고 해당 페이지에서 content들을 조작하였는데 무방한지 궁금합니다.
=> 네 내부에 chidlren으로 받는 요소들의 스타일은 해당 요소에서 컨트롤하는식으로 진행하는게 맞겠네요!

2022-02-17 06:12 UTC, jihongzzang commented on src/pages/ProductDetail/FavoriteModal.js
> +  return (
수정완료

2022-02-17 06:14 UTC, jihongzzang commented on src/pages/ProductDetail/ProductDetail.js
> +    return renderNum;
이부분 궁금했었는데 감사합니다!

2022-02-17 06:16 UTC, jihongzzang commented on src/pages/ProductDetail/FavoriteBtn.js
> +const sizes = {
수정완료!

2022-02-17 06:18 UTC, jihongzzang commented on src/pages/ProductDetail/FavoriteBtn.js
> +  }}
감사합니다.!

2022-02-17 06:23 UTC, jihongzzang commented on src/pages/ProductDetail/FavoriteModal.js
> +      <ModalWrapper onClick={e => e.stopPropagation()}>
이부분은 다음주 코드리팩토링 하면서 진행하겠습니다!!!

2022-02-18 03:20 UTC, younuk23 approved these changes
LGTM 👍

2022-02-18 03:21 UTC, younuk23 commented
Conflict 해결해주세요~!

2022-02-18 06:50 UTC, younuk23 approved these changes
LGTM 👍

2022-02-18 06:50 UTC, merged