[Feature/btn state manage]
wecode-bootcamp-korea/29-2nd-GREAM-frontend pull request #7
Opened 2022-02-17 14:07 UTC by jihongzzang

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 아이디, 비밀번호 입력창을 사용한 로그인 기능 구현 (예시)

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 로그인 입력 데이터 유효성 검사 (예시 - 프론트)
- 입력창에 변화가 일어날 때 마다 유효성 검사 함수가 실행된다.
- 유효성 검사 함수의 반환값(boolean)에 따라 버튼의 배경색과 disabled 속성이 변화한다.
- 테스트 방법 : `/login` 페이지 이동 >>> 로그인 input 데이터 입력

2. 로그인 데이터 처리 (예시 - 백엔드)
- 조건문과 정규식을 이용한 email과 password 유효성 검사를 진행
- 유효섬 검사를 통과하지 못 할 경우 에러 메시지를 반환 예외 처리 구현

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 사용자가 발생시킬 수 있는 다양한 예외 케이스에 대해 고민하게 되었습니다. (예시)
- 문자열 데이터 입력 시 마지막에 빈 문자열이 포함되어 있는 경우 데이터 처리가 올바르게 되지 않아 유효성 검사에 빈 문자열 제거하는 로직을 추가하였습니다. (예시)

<br />

## :: 기타 질문 및 특이 사항
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시)

2022-02-21 04:44 UTC, younuk23 requested changes
고생하셨습니다 지홍님 리뷰 확인 및 반영해주세요!

2022-02-21 04:44 UTC, younuk23 commented on src/pages/Config.js
> +const BASE_URL = 'http://15.164.48.155:8080/';
파일명 소문자로 시작하도록 변경해주면 좋겠네요!

2022-02-21 04:44 UTC, younuk23 commented on src/pages/ProductDetail/FavoriteModal.js
> +                  fullWidth
```suggestion
                  onClick={btnClick}
                  key={size.id}
                  name={size.name}
                  value={size.id}
                  color="lightGrey"
                  outline
                  fullWidth
```

value 명시적 부여하는 것들이랑, true값만 부여하는 것들 순서 구분지어서 좀 더 읽기좋게 해주는게 좋습니다!

2022-02-21 04:44 UTC, younuk23 commented on src/pages/ProductDetail/FavoriteModal.js
> +                        <FontAwesomeIcon icon={fasBookmark} size="1x" />
실질적으로 변하는 부분은 icon={fasBookmark or farBookmark}  인것 같은데 전체적으로 삼항연산자 적용할 필요 있을까요?
해당부분에만 삼항연산자 적용하는 식으로 바꾸는게 좋아보입니다!

2022-02-21 04:44 UTC, younuk23 commented on src/pages/ProductDetail/MarketPriceModal.js
> +    Large: false,
property name이 대문자로 시작하는 이유가 있나요? 특별한 이유 없으면 카멜케이스에 맞춰서 작성해주세요!

2022-02-21 04:44 UTC, younuk23 commented on src/pages/ProductDetail/ProductDetail.js
> +  };
```suggestion
  const ModalListObj = {
    1: (
      <FavoriteModal
        title="관심 상품 추가"
        confirmText="확인"
        productName={productName}
        productImg={productImg}
        productSizes={SIZE_INFO}
        productId={productId}
        onConfirm={onModalConfirm}
        btnClick={btnClick}
        isClickBtn={isClickBtn}
      />
    ),
    2: (
      <MarketPriceModal
        title="시세"
        productName={productName}
        productImg={productImg}
        productSizes={SIZE_INFO}
        productId={productId}
        onConfirm={onModalConfirm}
      />
    ),
  };
```

1, 2를 key 로 쓰는 것 보다는 의미가 드러나는 key 값을 쓰는게 좋아보입니다!

2022-02-21 04:47 UTC, younuk23 commented
- 기능구현을 하는 과정에서 좀 많은 고민들이 있었습니다. 특히 바꿔보고 싶은 부분이 btnClick 함수 ClickToggle 함수 onModalConfirm 부분에서 실제로 홈페이지들을 뜯어보는 과정에서 버튼을 눌렀을때 많은 이벤트들이 발생하였습니다. 따라서 이부분을 좀 분리해보고 싶었는데 이 세가지 함수의 경우 각각 하나의 함수들에서 많은 처리를 하지않나 싶은데 이럴때는 어떤식으로 다뤄야하는지 알고 싶습니다.
 => 한 함수에서 너무 많은 일들을 하고 있다고 생각될때는 일단 각각 함수가 어떤 역할을 하고 있는지 분석해보고, 만약 두가지 이상을 하고 있고 나눌 수 있을 것 같다라고 판단이서면 분리하는식으로 시도를 해보는게 좋습니다.
 그래서 작은 함수들로 다 분리를 한 다음, 실행이 되는 시점이 onClick 하나라면, 이 작은 함수들을 모아서 큰 동작을 하는 함수를 하나 만들고 onClick에 큰 함수를 할당하는 식으로 진행하면 되겠네요, 일단은 함수의 이름을 잘 지어보는것 부터 시작해보시면 좋을 것 같습니다. 지금은 btnClick, clickToggle 등 함수가 발생되는 시점이 이름으로 되어있는데 이렇게 지으면 무슨 동작을 하는지 파악하기도 힘들뿐더러 많은 기능을 한 함수에 넣어버리기 쉽습니다.
 만약 함수의 이름이 함수의 동작인 changeModal, closeModal, addProductToWishList 등으로 지어져있으면 만약 addProductToWishList 함수에서 다른 동작을 하기전에 한번 더 고민하고 다른 함수로 자연스럽게 분리하는식으로 되겠네요!

2022-02-21 05:44 UTC, jihongzzang commented on src/pages/Config.js
> +const BASE_URL = 'http://15.164.48.155:8080/';
반영완료

2022-02-21 05:48 UTC, jihongzzang commented on src/pages/ProductDetail/FavoriteModal.js
> +                        <FontAwesomeIcon icon={fasBookmark} size="1x" />
반영완료

2022-02-21 05:49 UTC, jihongzzang commented on src/pages/ProductDetail/FavoriteModal.js
> +                  fullWidth
반영완료

2022-02-21 05:54 UTC, jihongzzang commented on src/pages/ProductDetail/MarketPriceModal.js
> +    Large: false,
이부분 같은경우는 제가 상수데이터에 name 이 대문자로 시작해서 그렇게 작성했습니다. !!

2022-02-21 06:01 UTC, jihongzzang commented
질문에 상세히 답변해주셔서 감사합니다. 이미 올려져있는 pr들 먼저 모두 rebasing 과정후에 브랜치를 새로파서 수정하는 방식으로 해보겠습니다!!

2022-02-21 06:01 UTC, jihongzzang commented on src/pages/ProductDetail/ProductDetail.js
> +  };
반영완료

2022-02-21 10:06 UTC, younuk23 requested changes
찐찐막 수정 고고 해주세요!

2022-02-21 10:06 UTC, younuk23 commented on src/pages/Config.js
> +const BASE_URL = 'http://15.164.48.155:8080/';
반영안된것 같네요 git mv 명령어 이용해서 수정해주세요~!

2022-02-21 10:06 UTC, younuk23 commented on src/pages/ProductDetail/FavoriteModal.js
> +                        <FontAwesomeIcon icon={fasBookmark} size="1x" />
```suggestion
                        <FontAwesomeIcon icon={isClickBtn[size.name] ? fasBookmark : farBookMark} size="1x" />
```

2022-02-21 11:44 UTC, jihongzzang commented on src/pages/Config.js
> +const BASE_URL = 'http://15.164.48.155:8080/';
바꿨습니다!!

2022-02-21 12:08 UTC, jihongzzang commented on src/pages/Config.js
> +const BASE_URL = 'http://15.164.48.155:8080/';
반영완료하였습니다. vscode에서 자체적으로 파일이름을 바꾸면 안되는군요

2022-02-22 04:32 UTC, younuk23 approved these changes
LGTM 👍

2022-02-22 04:33 UTC, merged