[Feature/products list]
wecode-bootcamp-korea/29-2nd-GREAM-frontend pull request #8
Opened 2022-02-18 07:34 UTC by jaecoder222

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 상품리스트페이지 레이아웃

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1.상품리스트 레이아웃 작성
 slick slide구현 
2. fetch함수를 목데이터 구현, 통신 (
- 백엔드와 통신 완료후 목데이터로 작업

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- styled component 사용이 어렵고 복잡합니다.
-  slick slide구현 함에 있어 어려움이 있습니다.

<br />

## :: 기타 질문 및 특이 사항

2022-02-18 09:25 UTC, younuk23 requested changes
재형님 컴포넌트 잘 나누고 레이아웃도 잘 잡으셨네요!! 리뷰 확인 및 반영해주시고, 사이더에서 코멘트 달아준 부분도 해결해주세요! 💪

2022-02-18 09:25 UTC, younuk23 commented on src/components/ProductCard/ProductCard.js
> +import { fabookmark } from '@fortawesome/free-solid-svg-icons';
사용하지 않는 변수는 삭제해주세요!

2022-02-18 09:25 UTC, younuk23 commented on src/components/ProductCard/ProductCard.js
> +      <ProductLink href="#">
react-router-dom을 쓰고 있으니까 a tag보다는 Link 컴포넌트를 이용해주세요!

2022-02-18 09:25 UTC, younuk23 commented on src/pages/ProductsList/ProductsListComponents/Box.js
> +`;
스타일 컴포넌트 선언을 함수형 컴포넌트 안에서 하게 되면 매 렌더링마다 선언과 할당과정이 계속 일어나게 되서 비효율적입니다.다른 파일에서 하신 것 처럼 함수형컴포넌트와 export default 문 사이에서 진행해주세요!

2022-02-18 09:25 UTC, younuk23 commented on src/pages/ProductsList/ProductsListComponents/LeftFilter.js
> +  };
함수 이름이 modal인것 보다는 어떤 동작을 하는지 좀 더 명확하게 드러나는 이름을 사용해주세요!

2022-02-18 09:25 UTC, younuk23 commented on src/pages/ProductsList/ProductsListComponents/Listwrap.js
> +  `;
이전 코멘트와 마찬가지의 내용입니다! 전반적으로 확인 및 적용해주세요!

2022-02-18 09:25 UTC, younuk23 commented on src/pages/ProductsList/ProductsListComponents/RightFilter.js
> +  console.log(list);
테스트 마친 콘솔은 삭제해주세요!

2022-02-18 09:25 UTC, younuk23 commented on src/pages/ProductsList/ProductsListComponents/RightFilter.js
> +          })}
```suggestion
        {list.length > 0 &&
          list.map(({id, author, name, price, product_image}) => {
            return (
              <Card
                key={comment.id}
                product_image={comment.product_image[0].image}
                author={comment.author}
                name={comment.name}
                price={comment.price}
              />
            );
          })}
```
매개변수 자리에서 바로 구조분해할당해서 사용하면 좀 더 깔끔해지겠네요!

2022-02-21 01:27 UTC, jaecoder222 commented on src/pages/ProductsList/ProductsListComponents/RightFilter.js
> +  console.log(list);
삭제하였습니다!

2022-02-21 01:30 UTC, jaecoder222 commented on src/components/ProductCard/ProductCard.js
> +import { fabookmark } from '@fortawesome/free-solid-svg-icons';
삭제했씁니다!

2022-02-21 01:33 UTC, jaecoder222 commented on src/pages/ProductsList/ProductsListComponents/LeftFilter.js
> +import ModalCategory from './ModalCategory';
삭제했습니다.

2022-02-21 02:10 UTC, jaecoder222 commented on src/pages/ProductsList/ProductsListComponents/Box.js
> +`;
수정하였습니다!

2022-02-21 02:11 UTC, jaecoder222 commented on src/pages/ProductsList/ProductsListComponents/LeftFilter.js
> +  };
toggleMenu로 수정하였습닌다.

2022-02-21 02:13 UTC, jaecoder222 commented on src/pages/ProductsList/ProductsListComponents/Listwrap.js
> +  `;
수정하였습니다.

2022-02-21 02:16 UTC, jaecoder222 commented on src/pages/ProductsList/ProductsListComponents/RightFilter.js
> +          })}
수정하였습니다.

2022-02-21 02:36 UTC, jaecoder222 commented on src/components/ProductCard/ProductCard.js
> +      <ProductLink href="#">
수정하였습니다.

2022-02-21 04:51 UTC, younuk23 requested changes
재형님! 수정하셨다고 하는 사항들이 아직 다 반영이 안된 것 같습니다 아마 푸쉬가 안되신 것 같네요 file changed 탭에서 확인해보시고 반영해주세요!

2022-02-21 04:51 UTC, younuk23 commented on src/components/ProductCard/ProductCard.js
> +      <ProductLink href="#">
수정 사항 반영이 안된 것 같네요! 여전히 a tag인 것 같습니다

2022-02-22 04:34 UTC, younuk23 approved these changes
고생하셨습니다 재형님! 첫 머지 축하드립니다 🎉

2022-02-22 04:35 UTC, merged